package org.cloud.ssm.mapper;

import java.util.List;
import org.cloud.ssm.entity.Department;
import org.cloud.ssm.entity.DepartmentExample;

public interface DepartmentMapper {
    int deleteByPrimaryKey(Integer id);

    int insert(Department record);

    int insertSelective(Department record);

    List<Department> selectByExample(DepartmentExample example);

    Department selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(Department record);

    int updateByPrimaryKey(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     */
    int batchInsert(List<Department> list);
}