package org.cloud.ssm.mapper;

import java.util.List;
import org.cloud.ssm.entity.Employee;
import org.cloud.ssm.entity.EmployeeExample;

public interface EmployeeMapper {
    int deleteByPrimaryKey(Integer id);

    int insert(Employee record);

    int insertSelective(Employee record);

    List<Employee> selectByExample(EmployeeExample example);

    Employee selectByPrimaryKey(Integer id);

    int updateByPrimaryKeySelective(Employee record);

    int updateByPrimaryKey(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     */
    int batchInsert(List<Employee> list);
}