package org.cloud.ssm.mapper;

import java.util.List;
import org.cloud.ssm.entity.Menu;
import org.cloud.ssm.entity.MenuExample;

public interface MenuMapper {
    int deleteByPrimaryKey(Integer menuId);

    int insert(Menu record);

    int insertSelective(Menu record);

    List<Menu> selectByExample(MenuExample example);

    Menu selectByPrimaryKey(Integer menuId);

    int updateByPrimaryKeySelective(Menu record);

    int updateByPrimaryKey(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     */
    int batchInsert(List<Menu> list);
}